name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: Features
    label: feature
  - title: Bugfixes
    label: fix
  - title: Updates
    label: bump
template: |
  ## Changes

  $CHANGES
